### ISSUE TITLE
helpful discussion for Readme / final conglomeration error?

### ISSUE THREAD

**Issue by lowagner** [makapuf/bitbox-fmv#1]
for clarity, readme might be re-ordered and added to in this way:
- Save the following video https://www.youtube.com/watch?v=znO_m00s8II to dragons_lair_arcade_game_laserdisc.mp4
- Extract the audio track as mixdown.wav via `ffmpeg -i dragons_lair_arcade_game_laserdisc.mp4 mixdown.wav`.  [[[This step could be removed if just do the mixdown and bitbox reduction in one step in the frames/Makefile via post_render.py... `ffmpeg -i dragons_lair_arcade_game_laserdisc.mp4 -acodec pcm_u8 -ac 1 -af "volume=2.3"  -ar 16000 audio.wav` ]]] 
- Open the video_15fps.blend in Blender, then do Render->Render Animation.
- In Blender, change the editor back to `Text Editor` and run the python script `post_render.py` (alt+p).
- On the command line, run `make -j4 -f frames/Makefile`.
- Back in Blender, get to the `final_build.py` script and run it (alt+p).
- Back on the command line, type a `make`, to create the bitbox and emulator executable.

when i do the above steps and try to run the emulator, i get a scary yellow/red static to appear, with lots of angry white noise.  so let me know if any of the steps above are incorrect, or what else might be the issue!

**Comment by makapuf** [comment]
Hi. Thanks that seems much clearer. Now, I am not sure what went wrong nor can I retry it here. Can you run it with the binary data in the release ?

**Comment by lowagner** [comment]
frames.ani from the release works fine for my emulator version, so i must have made some error going through the steps...

**Comment by makapuf** [comment]
I'll try to remake the output. 
note that it would be funny to try it on another (libre) video

**Comment by makapuf** [comment]
note that generally i mixdown the file using blender command (save mixdown) but that shouldn't change anything.

**Comment by makapuf** [comment]
maybe we should also mention youtube-dl for automated dowloading ...

installed as `sudo apt-get install youtube-dl`
used as `youtube-dl -f  <format code> <url>`

**Comment by lowagner** [comment]
has dragons lair been released publically?  will some IP come for this git repository?

**Comment by makapuf** [comment]
OK, is your data file working on pc emulator ?

2016-02-24 23:30 GMT+01:00 Lucas O. Wagner notifications@github.com:

**Comment by lowagner** [comment]
not since i last checked, but it's ok if we have the binary release...

On Thu, Feb 25, 2016 at 4:40 PM, makapuf notifications@github.com wrote:

> OK, is your data file working on pc emulator ?
> 
> 2016-02-24 23:30 GMT+01:00 Lucas O. Wagner notifications@github.com:
> 
> > frames.ani from the release works fine for my emulator version, so i must
> > have made some error going through the steps...
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/makapuf/bitbox-fmv/issues/1#issuecomment-188485796.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/makapuf/bitbox-fmv/issues/1#issuecomment-189016030.

## 

"""
  lucas o. wagner
  lowagner.github.io
"""

**Comment by makapuf** [comment]
well, the instructions should work if we want to be able to do other
releases by example !

2016-02-26 0:16 GMT+01:00 Lucas O. Wagner notifications@github.com:

> not since i last checked, but it's ok if we have the binary release...
>

**Comment by lowagner** [comment]
here're somethings maybe strange:

when I do blender -> Render -> Render Animation, it only renders up to frame 2238, when I see that there are 19878 of them.  (I see you can change that in the Scene Render box, so maybe that wasn't saved correctly into the blend file.) 

also, when it converts the pngs into btcs, it says "y size 150 not a multiple of 4, will be cropped", but that's probably ok.

well it's still running the frames/Makefile, but I'm guessing it will be ok after that change above.

**Comment by lowagner** [comment]
nevermind the last "guessing it will be ok" -- i still have the same issue after rendering the whole batch -- angry kaleidoscope static.

perhaps i have the wrong resolution ?

**Comment by makapuf** [comment]
I'll try to look at it this weekend !

2016-02-26 14:23 GMT+01:00 Lucas O. Wagner notifications@github.com:

**Comment by makapuf** [comment]
yup, really think it comes from the resolution which should be 400x300 
I fixed it, please tell me if you see an improvement.

**Comment by lowagner** [comment]
ok, looks like things are progressing without cropping errors, though i still had to manually change the final frame in the blender file to 19878 or whatever before i did "Render->Render Animation".

in case I make a video about some of the current bitbox games, the btc4.py script is essentially doing your compression algorithm as in http://bitboxconsole.blogspot.nl/2014/05/playing-titanfall-and-super-mario-3d.html#more, right?

**Comment by makapuf** [comment]
Yes exactly the same.
Le 28 févr. 2016 5:41 AM, "Lucas O. Wagner" notifications@github.com a
écrit :

**Comment by lowagner** [comment]
ok, it's working now!  do we know why, on some of the death scenes, it skips to a frame or two of dirk escaping the scene, but then it jumps to him dying?

**Comment by makapuf** [comment]
maybe because the encoding does not fit exactly the declaration of the
frames (maybe because of the video being different?)
The mechanisme is so simple, it should really work on a frame by frame
basis.

Does it happen with the provided binary ?

2016-02-29 4:37 GMT+01:00 Lucas O. Wagner notifications@github.com:
